[en]
  title = "鬼斯通のblog物语"
  languageName = "中文"
  weight = 3
  languagedir = "ltr"
  contentdir = "content/en"

[ko]
  title = "Hugo Zzo Theme"
  languageName = "한국어"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/ko"

# 实验
# [cn]
#   title = "Hugo Zzo Theme"
#   languageName = "中文"
#   weight = 1
#   languagedir = "ltr"
#   contentdir = "content/cn"