[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 0

[[main]]
  identifier = "series"
  name = "系列"
  url = "series/"
  weight = 1

[[main]]
  parent = "series"
  name = "面试"
  url = "series/interview"

[[main]]
  parent = "series"
  name = "开源框架"
  url = "series/"

[[main]]
  identifier = "archive"
  name = "档案馆"
  url = "archive"
  weight = 3

[[main]]
  identifier = "posts"
  name = "文章"
  url = "posts"
  weight = 6

[[main]]
  identifier = "presentation"
  name = "Presentation"
  url = "presentation"
  weight = 4


[[main]]
  identifier = "category"
  name = "分类"
  url = "categories/"
  weight = 2

[[main]]
  parent = "category"
  name = "Golang"
  url = "categories/golang"

[[main]]
  parent = "category"
  name = "LeetCode"
  url = "categories/leetcode"

[[main]]
  parent = "category"
  name = "框架"
  url = "categories/frame"

[[main]]
  parent = "category"
  name = "知识"
  url = "categories/code"

[[main]]
  identifier = "gallery"
  name = "藏库"
  url = "gallery"
  weight = 5
    
[[main]]
  parent = "gallery"
  name = "Cartoon"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "Photo"
  url = "gallery/photo"


[[main]]
  identifier = "showcase"
  name = "Showcase"
  url = "showcase"
  weight = 7

[[main]]
  identifier = "publication"
  name = "Pub"
  url = "publication"
  weight = 8